optimizer:
  #  Adam-oriented deep learning
  _target_: torch.optim.Adam
  #  These are all default parameters for the Adam optimizer
  lr: 5e-4
  betas: [ 0.9, 0.999 ]
  eps: 1e-08
  weight_decay: 1e-7

use_lr_scheduler: True
lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingWarmRestarts
  T_0: 500
  T_mult: 1
  eta_min: 1e-5
