python -W ignore conditional_generation.py \
    --model_path /home/gabeguo/hydra/singlerun/2024-04-23/mp_20_moka \
    --num_starting_points 25 \
    --num_candidates 5 \
    --lr 1e-2 \
    --min_lr 1e-4 \
    --l2_penalty 2e-4 \
    --num_tested_materials 200 \
    --label _moka_sinc100_ \
    --num_gradient_steps 1000 \
    --num_atom_lambda 0.1 \
    --n_step_each 100 \
    --composition_lambda 0.1 \
    --l1_loss \
    --r_min 0 \
    --r_max 30 \
    --wave_source MoKa \
    --output_dir paper_results_PRELIM \
    --start_from_init /home/gabeguo/cdvae_xrd/paper_results_PRELIM/_moka_sinc100_