python -W ignore conditional_generation.py \
    --model_path /home/gabeguo/cdvae_xrd/outputs/singlerun/2024-09-11/mp_20_sinc100_REAL_DATA \
    --num_starting_points 200 \
    --num_candidates 20 \
    --lr 0.1 \
    --min_lr 1e-4 \
    --l2_penalty 2e-4 \
    --num_tested_materials 200 \
    --label _jamie_data_ \
    --num_gradient_steps 5000 \
    --num_atom_lambda 0.1 \
    --n_step_each 100 \
    --composition_lambda 0.1 \
    --l1_loss \
    --r_min 0 \
    --r_max 30 \
    --output_dir paper_results_PRELIM
